version: '3.8'
services:
  im:
    build:
      context: .
      dockerfile: .dockerfile
    restart: always
    container_name: im
    env_file:
      - .env
    environment:
      REDIS_DB_HOST: ${REDIS_DB_HOST}
      REDIS_DB_PORT: ${REDIS_DB_PORT}
      CLICKHOUSE_DB_HOST: ${CLICKHOUSE_DB_HOST}
      CLICKHOUSE_DB_USERNAME: ${CLICKHOUSE_DB_USERNAME}
      CLICKHOUSE_DB_PASSWORD: ${CLICKHOUSE_DB_PASSWORD}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_DB_USERNAME: ${MYSQL_DB_USERNAME}
      MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mysql
      - clickhouse

  redis:
    image: redis:alpine
    restart: always
    container_name: im_redis
    ports:
      - 16379:6379

  mysql:
    image: bitnami/mysql:8.3.0
    container_name: im_mysql
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: im
    ports:
      - 13306:3306
    
      
  clickhouse:
    image: clickhouse:24.12
    container_name: im_clickhouse
    env_file:
      - .env
    environment:
      CLICKHOUSE_DB: im
      CLICKHOUSE_USER: ${CLICKHOUSE_DB_USERNAME}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_DB_PASSWORD}
    ports:
      - 18123:8123