version: '3.8'
services:
  im:
    build:
      context: .
      dockerfile: .dockerfile
    restart: always
    container_name: im
    env_file:
      - .env
    environment:
      REDIS_DB_HOST: ${REDIS_DB_HOST}
      REDIS_DB_PORT: ${REDIS_DB_PORT}
      CLICKHOUSE_DB_HOST: ${CLICKHOUSE_DB_HOST}
      CLICKHOUSE_DB_USERNAME: ${CLICKHOUSE_DB_USERNAME}
      CLICKHOUSE_DB_PASSWORD: ${CLICKHOUSE_DB_PASSWORD}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_DB_USERNAME: ${MYSQL_DB_USERNAME}
      MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      ARTEMIS_HOST: ${ARTEMIS_HOST}
      ARTEMIS_PORT: ${ARTEMIS_PORT}
      ARTEMIS_USER: ${ARTEMIS_USER}
      ARTEMIS_PASSWORD: ${ARTEMIS_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mysql
      - clickhouse
      - artemis

  redis:
    image: redis:alpine
    restart: always
    container_name: im_redis
    ports:
      - 16379:6379

  mysql:
    image: bitnami/mysql:8.3.0
    restart: always
    container_name: im_mysql
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: im
    ports:
      - 13306:3306
    
      
  clickhouse:
    image: clickhouse:24.12
    restart: always
    container_name: im_clickhouse
    env_file:
      - .env
    environment:
      CLICKHOUSE_DB: im
      CLICKHOUSE_USER: ${CLICKHOUSE_DB_USERNAME}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_DB_PASSWORD}
    ports:
      - 18123:8123

  artemis:
    image: apache/activemq-artemis:2.39.0-alpine
    container_name: im_activemq-artemis
    env_file:
      - .env
    environment:
      ARTEMIS_USER: ${ARTEMIS_USER}
      ARTEMIS_PASSWORD: ${ARTEMIS_PASSWORD}
      ANONYMOUS_LOGIN: true
    ports:
      - 8161:8161   # Web管理界面
      - 61616:61616 # AMQP
      - 61613:61613 # STOMP
      - 5672:5672   # MQTT

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000  # API 端口
      - 9001:9001  # 控制台端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
