server:
  port: 8080

spring:
  application.name: im
  main.web-application-type: SERVLET
  resources:
    add-mappings: false
  data:
    redis:
      database: 0
      host: ${REDIS_DB_HOST:127.0.0.1}
      port: ${REDIS_DB_PORT:16379}
  datasource:
    dynamic:
      primary: mysql
      strict: false
      datasource:
        clickhouse:
          url: jdbc:clickhouse://${CLICKHOUSE_DB_HOST:127.0.0.1:18123}/im
          username: ${CLICKHOUSE_DB_USERNAME:default}
          password: ${CLICKHOUSE_DB_PASSWORD:example}
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
        mysql:
          url: jdbc:mysql://${MYSQL_DB_HOST:127.0.0.1:13306}/im
          username: ${MYSQL_DB_USERNAME:root}
          password: ${MYSQL_DB_PASSWORD:example}
          driver-class-name: com.mysql.cj.jdbc.Driver
  artemis:
    mode: native
    host: ${ARTEMIS_HOST:127.0.0.1}
    port: ${ARTEMIS_PORT:61616}
    user: ${ARTEMIS_USER:artemis}
    password: ${ARTEMIS_PASSWORD:artemis}

mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  file:
    name: logs/app.log  # 指定日誌文件名
    # path: logs         # 或者僅指定目錄
  level:
    root: info

stomp:
  mq:
    relay-host: ${ARTEMIS_HOST:127.0.0.1}
    relay-port: ${ARTEMIS_PORT:61616}
    login: ${ARTEMIS_USER:artemis}
    passcode: ${ARTEMIS_PASSWORD:artemis}
    enable: true

  kafka:
    enable: false
    bootstrap-servers: ${KAFKA_HOST:127.0.0.1}:${KAFKA_PORT:9094}
    properties:
      enable.idempotence: false

    producer:
      retries: 5
      compression-type: lz4
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

    consumer:
      group-id: ${KAFKA_GROUP:kafka_default_group}
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

    listener:
      concurrency: 10
      idle-event-interval: 60000

    admin:
      auto-create: true

minio:
  endpoint: ${MINIO_URL:http://127.0.0.1:9000}
  accessKey: ${MINIO_ROOT_USER:minioadmin}
  secretKey: ${MINIO_ROOT_PASSWORD:minioadmin}

livekit:
  url: ${LIVEKIT_URL:http://127.0.0.1:7880}
  key: ${LIVEKIT_API_KEY:livekit_api_key}
  secret: ${LIVEKIT_API_SECRET:this_is_livekit_secret_key_for_test}

front-end:
  url: "http://localhost:5173"
  allPermitPaths: [ "/user/register", "/user/login", "/swagger-ui/**", "/v3/api-docs/**", "/ws/**" ]

webhook:
  enabled: false
  url: ""
  accessKey: ""
  event:
    APPLY_FRIEND: ""