spring:
  port: 8080
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:clickhouse://127.0.0.1:18123/im
    driverClassName: com.clickhouse.jdbc.ClickHouseDriver
    username: default
    password: example

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
