spring:
  port: 8080
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 5s
      connect-timeout: 5s
  datasource:
    dynamic:
      primary: gamedb
      strict: false
      clickhouse:
        url: jdbc:clickhouse://127.0.0.1:8123/im
        username: default
        password: example
        driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      mysql:
        url: jdbc:mysql://127.0.0.1:3306/im
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

tio:
  websocket:
    server:
      port: 9876
      heartbeat-timeout: 600000

#    ssl:
#      enabled: true
#      keyStore: classpath:ssl/keystore.jks
#      trustStore: classpath:ssl/keystore.jks
#      password: 214323428310224
    #是否支持集群，集群开启需要redis
    cluster:
      enabled: false
      all: true
      group: true
      ip: true
      user: true
