spring:
  application.name: im
  port: 8080
  resources:
    add-mappings: false
  data:
    redis:
      database: 0
      host: ${REDIS_DB_HOST:127.0.0.1}
      port: ${REDIS_DB_PORT:16379}
  datasource:
    dynamic:
      primary: mysql
      strict: false
      datasource:
        clickhouse:
          url: jdbc:clickhouse://${CLICKHOUSE_DB_HOST:127.0.0.1:18123}/im
          username: ${CLICKHOUSE_DB_USERNAME:default}
          password: ${CLICKHOUSE_DB_PASSWORD:example}
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
        mysql:
          url: jdbc:mysql://${MYSQL_DB_HOST:127.0.0.1:13306}/im
          username: ${MYSQL_DB_USERNAME:root}
          password: ${MYSQL_DB_PASSWORD:example}
          driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  file:
    name: logs/app.log  # 指定日誌文件名
    # path: logs         # 或者僅指定目錄
  level:
    root: info

tio:
  websocket:
    server:
      port: 9999
      heartbeat-timeout: 600000

#    ssl:
#      enabled: true
#      keyStore: classpath:ssl/keystore.jks
#      trustStore: classpath:ssl/keystore.jks
#      password: 214323428310224
    #是否支持集群，集群开启需要redis
    cluster:
      enabled: false
      all: true
      group: true
      ip: true
      user: true
