spring:
  port: 8080
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema: classpath:sql/*-schema.sql
    data: classpath:sql/*-data.sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
