spring:
  port: 8080
  resources:
    add-mappings: false
  threads:
    virtual:
      enabled: true
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 16379
  datasource:
    dynamic:
      primary: mysql
      strict: false
      datasource:
        clickhouse:
          url: jdbc:clickhouse://127.0.0.1:18123/im
          username: default
          password: example
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
        mysql:
          url: jdbc:mysql://127.0.0.1:13306/im
          username: root
          password: example
          driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  file:
    name: logs/app.log  # 指定日誌文件名
    # path: logs         # 或者僅指定目錄
  level:
    root: info

tio:
  websocket:
    server:
      port: 9999
      heartbeat-timeout: 600000

#    ssl:
#      enabled: true
#      keyStore: classpath:ssl/keystore.jks
#      trustStore: classpath:ssl/keystore.jks
#      password: 214323428310224
    #是否支持集群，集群开启需要redis
    cluster:
      enabled: false
      all: true
      group: true
      ip: true
      user: true
